apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::909945135562:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OMTTMBH9XWXV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-25T21:25:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1118"
  uid: 032eecc1-4a84-42d4-9312-3da3cd7000a7
